Update Poetry configuration for install-poetry.py
python-poetry/poetry#3706

Poetry has a new install script, install-poetry.py, which alters the
requirements for adding Poetry to `$PATH`. One simple way to add Poetry
to `$PATH` is to `export PATH=$HOME/.local/bin:$PATH`, which adds the
~/.local/bin directory (it's also used by pipx, so it's a good option)
to `$PATH`, then `export POETRY_HOME=$HOME/.local`, which tells Poetry
to install itself into the ~/.local/bin directory.

diff --git a/script/strap-after-setup b/script/strap-after-setup
--- a/script/strap-after-setup
+++ b/script/strap-after-setup
@@ -21,16 +21,16 @@ fi
 
 ### Install user Python packages
 if command -v python3 &>/dev/null; then
-  if ! command -v poetry &>/dev/null; then
-    curl -fsSL $RAW/python-poetry/poetry/HEAD/get-poetry.py | python3 -
-  fi
   if ! command -v pipx &>/dev/null; then
     python3 -m pip install --user pipx
     python3 -m pipx ensurepath
   fi
+  if ! command -v poetry &>/dev/null; then
+    curl -fsSL $RAW/python-poetry/poetry/HEAD/install-poetry.py | python3 -
+  fi
   "$HOME"/.dotfiles/script/python-user-packages.sh
 else
-  echo "Python 3 not found. Skipping Poetry and pipx installs."
+  echo "Python 3 not found. Skipping pipx and Poetry installs."
 fi
 
 ### Install VSCode extensions
