Run `bootstrap.sh` in GitHub Actions
This commit will add a job to the GitHub Actions workflow that runs
`bootstrap.sh` in GitHub Actions, then re-runs it to check idempotence.

The `HOMEBREW_BUNDLE_CASK_SKIP` environment variable will be used to
skip cask installs. Although cask installs are mostly successful in CI,
occasional errors may be seen, so it's more practical to skip them. The
Homebrew Bundle command `brew bundle list --cask --quiet` will be used,
with spaces replacing newlines, as `HOMEBREW_BUNDLE_CASK_SKIP` expects a
space-separated string (https://docs.brew.sh/Manpage#bundle-subcommand).

The `HOMEBREW_BUNDLE_MAS_SKIP` environment variable will be used to
skip Mac App Store installs, as these require an AppleID login. There is
a Homebrew bundle command provided for listing Mac App Store apps,
`brew bundle list --mas --quiet`, but apps may have spaces in the names,
and `HOMEBREW_BUNDLE_MAS_SKIP` requires apps to be separated by spaces.
The solution is to parse `mas` IDs from the Brewfile, add them to a
space-separated string, and set `HOMEBREW_BUNDLE_MAS_SKIP` to the string
(Homebrew/homebrew-bundle#525, Homebrew/homebrew-bundle#529).

The `test` job in the GitHub Actions `ci` workflow takes about 30
minutes to run, so it will be limited to PRs or `workflow_dispatch`.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,3 +40,33 @@ jobs:
           sudo curl -fsSL -o "$sh_bin" "${sh_url}/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_${os}_amd64"
           sudo chmod +x "$sh_bin"
       - run: shfmt -d -f -i 2 .
+  test:
+    if: ${{ github.event_name != 'push' }}
+    needs: [lint]
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [macos-latest, ubuntu-latest]
+    timeout-minutes: 60
+    env:
+      STRAP_CI: 1
+      STRAP_DEBUG: 1
+    steps:
+      - uses: actions/checkout@v2
+      - name: Clean up Homebrew
+        run: |
+          command -v brew &>/dev/null && brew test-bot --only-cleanup-before ||
+            echo "Homebrew not found."
+      - name: Clean up macOS
+        if: startsWith(runner.os, 'macOS')
+        run: |
+          sudo rm -rf /usr/local/Caskroom /usr/local/Homebrew /usr/local/bin/brew \
+            /usr/local/.??* /Applications/Xcode.app /Library/Developer/CommandLineTools
+      - name: Run bootstrap.sh
+        run: bash bootstrap.sh
+      - name: Rerun bootstrap.sh to test idempotence
+        run: bash bootstrap.sh
+      - name: Check Homebrew configuration
+        run: brew config
+      - name: Check for potential problems with brew doctor
+        run: brew doctor || echo "Potential problems detected. See output for details."
